version: 1.2.0

feed_types:
  political_news:
    ttl_days: 1
    similarity_threshold: 90

colors:
  default: 15844367
  government: 3447003

rss:
  - name: CDC News Releases
    url: https://tools.cdc.gov/api/v2/resources/media/404952.rss
    tags: [government]
    type: political_news

  - name: State Dept. News
    url: https://www.state.gov/rss
    tags: [government]
    type: political_news

  - name: Treasury Dept. News
    url: https://home.treasury.gov/rss.xml
    tags: [government]
    type: political_news

  - name: CNN Politics
    url: https://rss.cnn.com/rss/cnn_allpolitics.rss
    tags: [mainstream]
    type: political_news

  - name: NYT Politics
    url: https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml
    tags: [mainstream]
    type: political_news

  - name: Washington Post Politics
    url: https://feeds.washingtonpost.com/rss/politics
    tags: [mainstream]
    type: political_news

  - name: Vox Politics
    url: https://www.vox.com/rss/index.xml
    tags: [left]
    type: political_news

  - name: Salon
    url: https://www.salon.com/feed
    tags: [left]
    type: political_news

  - name: MSNBC Latest
    url: https://feeds.nbcnews.com/msnbc/public/news
    tags: [mainstream]
    type: political_news

  - name: Fox News Politics
    url: https://moxie.foxnews.com/google-publisher/politics.xml
    tags: [right]
    type: political_news

  - name: Breitbart
    url: https://feeds.feedburner.com/breitbart
    tags: [right]
    type: political_news

  - name: NPR Politics
    url: https://feeds.npr.org/1014/rss.xml
    tags: [mainstream]
    type: political_news

  - name: Mother Jones
    url: https://www.motherjones.com/feed/
    tags: [left]
    type: political_news

html:
  - name: USA.gov
    url: https://www.usa.gov
    selector: "article"
    tags: [government]
    type: political_news

  - name: White House News
    url: https://www.whitehouse.gov
    selector: "article"
    tags: [government]
    type: political_news

  - name: Congress.gov
    url: https://www.congress.gov
    selector: "article"
    tags: [government]
    type: political_news

  - name: Supreme Court
    url: https://www.supremecourt.gov
    selector: "article"
    tags: [government]
    type: political_news

  - name: Federal Register
    url: https://www.federalregister.gov
    selector: "article"
    tags: [government]
    type: political_news

  - name: DoD News
    url: https://www.defense.gov/News/News-Releases/
    selector: "article"
    tags: [government]
    type: political_news

  - name: EPA Newsroom
    url: https://www.epa.gov/newsroom
    selector: "article"
    tags: [government]
    type: political_news

  - name: Ed.gov News
    url: https://www.ed.gov/news
    selector: "article"
    tags: [government]
    type: political_news

categories: {}
