name: News Feed

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '*/24 * * * *'   # every 24 minutes

jobs:
  scrape_and_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run News Feed Bot
        run: python3 cli.py
